### ISSUE TITLE
very easy and simple is your code for beginner 

### ISSUE THREAD

**Issue by wishrohitv** [antorix/KivyLoadSave#1]
i know it's not much necessary but you can include mp3 and text files on repo for reference 
great work 🔥
i'm also struggling with this

**Comment by antorix** [comment]
> i know it's not much necessary but you can include mp3 and text files on repo for reference great work 🔥 i'm also struggling with this

Ok, I'm adding a .txt file. As for MP3, no, you don't load it. It's the program itself which creates an EMPTY .mp3 file programmatically. It just writes a zero string ("") to it, so technically it's a text file, not MP3. I did it just to demonstrate how Android automatically places an .mp3 file to the Music folder looking at its extension. If you call it .jpg, it will go to your Images folder, etc.

**Comment by wishrohitv** [comment]
thank you very much for your explanation sir
